### ISSUE TITLE
How to change memory in Helyx-OS

### ISSUE THREAD

**Issue by KoalaMau** [ENGYS/HELYX-OS#41]
Good evening,

I am a university student, and I have been having a technical problem. For my master thesis I am using Helyx-os to generate the mesh, however I have a problem in one of the geometries. When I go to mesh my inlet has is a quarter circle with a radius of 0.8mm and so I need a very small base mesh spacing but as I only have 1gb of memory available, when I reduce the base mesh spacing of the kill process, how could I increase the available memory, if that is the problem of the inlet not appearing in the mesh. I have a computer with 16gb and only appears 1 gb in Helyx-OS, how can I change that?

Thanks,
Tiago Morão

**Comment by HELYX-OS** [comment]
Hi KoalaMau,

I do not understand a couple of things:
1) your laptop has 16 gb of ram correct?
2) when you reduce the base mesh spacing and you press "Create" mesh...does the mesher runs fine?
3) the 1gb of memory should not be the problem here, anyway you can change it by going to `<INSTALLATION_PATH>/Engys/HELYX-OS/v2.4.0/bin/launcher.conf" `
and change line 55 which should read 
`"OPTIONS=$OPTIONS" -Xmx1024m"`
and change it to 
`"OPTIONS=$OPTIONS" -Xmx2048m"`
for having 2gb of memory.

Hope this helps
