### ISSUE TITLE
Manual entries removed from controlDict

### ISSUE THREAD

**Issue by attesz86** [ENGYS/HELYX-OS#7]
If the user adds manual entries such as functionObjects, these will be removed when running the solver. Is it in the pipe to remove this "feature"?

**Comment by HELYX-OS** [comment]
Hi,

in order to achieve this, you need to use the Custom Interface.
Steps:
1) Right-click on the "Custom/system" leaf on the tree and select "Add"
2) On the dialog select "Type>Dictionary" and "Name>controlDict" and press OK
3) On the editor remove all the entries (except for the header)
4) Add the function objects and press OK.

Cheers

**Comment by attesz86** [comment]
Hi, thanks for the reply. I missed the 3. step, that's why it was not working.

Best regards!
